### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/osprey#103]
We should cut a v1.0 release and upload it to pypi at some point

Some TODOs:

- [x] fix bug when user `mdtraj` dataset loader (https://github.com/msmbuilder/osprey/pull/104)
- [x] fix PCA `ValueError` bug (https://github.com/msmbuilder/osprey/issues/105)
- [x] have travis upload msmbuilder.org/osprey (https://github.com/msmbuilder/osprey/issues/100, https://github.com/msmbuilder/osprey/pull/108)
- [x] log warping of int (https://github.com/msmbuilder/osprey/issues/95)
- [x] nan checks and handling (https://github.com/msmbuilder/osprey/issues/73, https://github.com/msmbuilder/osprey/issues/75)
- [x] filter by project name (https://github.com/msmbuilder/osprey/issues/23)
- [x] add msmb test (https://github.com/msmbuilder/osprey/issues/112, https://github.com/msmbuilder/osprey/pull/115)
- [x] design/add a logo (https://github.com/msmbuilder/osprey/issues/114)
- [x] remove references to MOE (https://github.com/msmbuilder/osprey/issues/119)
- [x] fix `current_best` bug (https://github.com/msmbuilder/osprey/issues/121, https://github.com/msmbuilder/osprey/pull/122)
- [x] add sparse matrix support (https://github.com/msmbuilder/osprey/issues/123)
- [x] fix bounds in `jump` (https://github.com/msmbuilder/osprey/issues/129)
- [x] fix plot error for 1 trial (https://github.com/msmbuilder/osprey/issues/125, https://github.com/msmbuilder/osprey/pull/134)
- [x] update docs (https://github.com/msmbuilder/osprey/issues/124, https://github.com/msmbuilder/osprey/issues/128)
- [x] eval_scope issues (https://github.com/msmbuilder/osprey/issues/142)

**Comment by mpharrigan** [comment]
Consider releasing a 1.0 version at some point

**Comment by cxhernandez** [comment]
When we don't even have proper doc deployment?!

**Comment by cxhernandez** [comment]
Okay once msmb v3.4 is done, we can release osprey v1.0

**Comment by cxhernandez** [comment]
Alright, I think we're all ready to release v1.0

**Comment by cxhernandez** [comment]
@rmcgibbo: When you get a chance, could you add me and @mpharrigan as maintainers on pypi?
